# Generated by Django 4.0.1 on 2022-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'Inactive'), ('AboutToExpire', 'Abouttoexpire'), ('Cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
    ]
