# Generated by Django 4.0.1 on 2022-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='branches',
            field=models.CharField(default='branch 1', max_length=100),
            preserve_default=False,
        ),
    ]
